version: "3.8"
services:
  db:
    container_name: staff_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backups:/usr/src/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: staff_docker
      PGDATA: /var/lib/postgresql/data/11-5