image: node:latest
before_script:
  - 'node -v'
  - 'npm -v'
stages:
  - build
  - deploy
Build:
  stage: build
  script:
    - 'npm i'
    - 'npm run build-stage'
  artifacts:
    paths:
      - build
Deploy:
  stage: deploy
  only:
    - dev
    - stage
  script:
   - 'which ssh-agent || ( apk update && apk add openssh-client git )'
   - eval $(ssh-agent -s)
   - echo "$HOST"
   - echo "$PORT"
   - echo "$STAGE_PRIVATE_KEY"
   - echo "$STAGE_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   - ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
   - ssh -p $PORT ubuntu@$HOST "rm -rf ~/internal-apps/_tmp_staff/"
   - ssh -p $PORT ubuntu@$HOST "mkdir ~/internal-apps/_tmp_staff/"
   - ssh -p $PORT ubuntu@$HOST "mv ~/internal-apps/fusion-staff/build/* ~/internal-apps/_tmp_staff/"
   - scp -P $PORT -r build/* ubuntu@$HOST:~/internal-apps/fusion-staff/build
